### ISSUE TITLE
clang little issues

### ISSUE THREAD

**Issue by vilkun** [kmammou/v-hacd#111]
Hello, I prepared patch, to fix clang issues, 'variable shadows other', variable order. You can apply it on top of 'master' branch:
git apply [vhacd.txt](https://github.com/kmammou/v-hacd/files/8780409/vhacd.txt)

Also you can add description about VHACD_DISABLE_THREADING as for ENABLE_VHACD_IMPLEMENTATION, because clang raised error, so I added it like VHACD_DISABLE_THREADING=0

**Comment by jratcliff63367** [comment]
Your patch has been applied and pushed to master.
