### ISSUE TITLE
Create release/tag for version 4.0

### ISSUE THREAD

**Issue by kevinzakka** [kmammou/v-hacd#113]
Hello,

Thanks for the great library! Would it be possible to create a release + tag for the newest 4.0 version so that I can peg against that version in my packages?

Thanks!

**Comment by kevinzakka** [comment]
Hi, any updates on this? It costs nothing and makes it so that libraries that depend on this can peg to a specific version :)

**Comment by jratcliff63367** [comment]
Sorry, I actually don't know what you are asking for. What would be the git command for that?

**Comment by kevinzakka** [comment]
@jratcliff63367 No worries, no need for git, you can do it from GitHub, see [here](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository).

LMK if you have questions

**Comment by jratcliff63367** [comment]
Done.

**Comment by kevinzakka** [comment]
Cheers @jratcliff63367 !
