### ISSUE TITLE
Add an argument to set log path

### ISSUE THREAD

**Issue by alters-mit** [kmammou/v-hacd#120]
The old version of VHACD had a `--log_path` argument. It would be nice to have this option in VHACD 4 or to have the option to suppress logging.

**Comment by jratcliff63367** [comment]
I can add that to the example test app, but just FYI, the API already fully supports this as well.

**Comment by jratcliff63367** [comment]
Submitted. If you pass '-l false' then the logging spew will be suppressed during computation.
