### ISSUE TITLE
No meshes to process error on osx

### ISSUE THREAD

**Issue by kristofgiber** [kmammou/v-hacd#13]
I'm on Mac. After installing the blender plugin and adding the //v-hacd-master/bin/osx/testVHACD path to field VHAC, When I press OK on the pop-up window to start the convex decomposition, it does nothing just gives an error 'no meshes to process!'. Despite my mesh being selected in Object mode. 

I've tried it with a simple mesh such as a cube mesh and gives the same error. I've also tried adding the osx path inside 'bin-no-ocl' and 'bin-no-ocl-omp' folders instead, same error. I'm also not sure if I need to change the 'add V-HACD paths preset' field or only to add the path to 'path to testVHACD executable.

I've identified one problem as it says 'dyld: Library not loaded: /opt/local/lib/libgcc/libgomp.1.dylib'
My gcc folder is not in /opt/local. After placing it there it starts the convex decomposition. I think there should be a field in the gui that allows for specifying the path to gcc.

However, even after I've copied my gcc to the above path, initiating VHACD results in a few minutes of processing with log in terminal, but in the end, without any error message in terminal, the 'no meshes to process!' error shows up again in Blender and no ACD mesh is created. 
I copy here the terminal log just in case:

Exporting mesh for V-HACD: /var/folders/b8/8bjj90812dqd2bdgzqllpmgm0000gn/T/Suzanne.off...
Running V-HACD...
/Users/user/Code/v-hacd-master/bin/osx/testVHACD --input "/var/folders/b8/8bjj90812dqd2bdgzqllpmgm0000gn/T/Suzanne.off" --resolution 100000 --depth 20 --concavity 0.0025 --planeDownsampling 4 --convexhullDownsampling 4 --alpha 0.05 --beta 0.05 --gamma 0.00125 --pca 0 --mode 0 --maxNumVerticesPerCH 32 --minVolumePerCH 0.0001 --output "/var/folders/b8/8bjj90812dqd2bdgzqllpmgm0000gn/T/Suzanne.wrl" --log "/var/folders/b8/8bjj90812dqd2bdgzqllpmgm0000gn/T/Suzanne_log.txt"

+ OpenCL (ON)
	 Number of OpenCL platforms: 1
	 OpenCL platform [0]
		CL_PLATFORM_NAME: FULL_PROFILE
		CL_PLATFORM_VENDOR: OpenCL 1.2 (Dec  8 2015 17:02:20)
		CL_PLATFORM_VERSION: Apple
		CL_PLATFORM_PROFILE: Apple
		CL_PLATFORM_EXTENSIONS: cl_APPLE_SetMemObjectDestructor cl_APPLE_ContextLoggingFunctions cl_APPLE_clut cl_APPLE_query_kernel_names cl_APPLE_gl_sharing cl_khr_gl_event
	 Using OpenCL platform [0]
	 Number of OpenCL devices: 2
	 OpenCL device [0]
		CL_DEVICE_NAME: Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz
		CL_DEVICE_PROFILE: FULL_PROFILE
		CL_DEVICE_VENDOR: Intel
		CL_DEVICE_VERSION: OpenCL 1.2 
		CL_DRIVER_VERSION: 1.1
		CL_DEVICE_EXTENSIONS: cl_APPLE_SetMemObjectDestructor cl_APPLE_ContextLoggingFunctions cl_APPLE_clut cl_APPLE_query_kernel_names cl_APPLE_gl_sharing cl_khr_gl_event cl_khr_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_image2d_from_buffer cl_APPLE_fp64_basic_ops cl_APPLE_fixed_alpha_channel_orders cl_APPLE_biased_fixed_point_image_formats cl_APPLE_command_queue_priority
		CL_DEVICE_VERSION: OpenCL 1.2 
		CL_DEVICE_ADDRESS_BITS: 64
		CL_DEVICE_GLOBAL_MEM_CACHELINE_SIZE: 4194304
		CL_DEVICE_MAX_CLOCK_FREQUENCY: 1700
		CL_DEVICE_MAX_COMPUTE_UNITS: 4
		CL_DEVICE_MAX_CONSTANT_ARGS: 8
		CL_DEVICE_MAX_READ_IMAGE_ARGS: 128
		CL_DEVICE_MAX_SAMPLERS: 16
		CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS: 3
		CL_DEVICE_MAX_WRITE_IMAGE_ARGS: 8
		CL_DEVICE_MEM_BASE_ADDR_ALIGN: 1024
		CL_DEVICE_MIN_DATA_TYPE_ALIGN_SIZE: 128
		CL_DEVICE_PREFERRED_VECTOR_WIDTH_CHAR: 16
		CL_DEVICE_PREFERRED_VECTOR_WIDTH_SHORT: 8
		CL_DEVICE_PREFERRED_VECTOR_WIDTH_INT: 4
		CL_DEVICE_PREFERRED_VECTOR_WIDTH_LONG: 2
		CL_DEVICE_PREFERRED_VECTOR_WIDTH_FLOAT: 4
		CL_DEVICE_PREFERRED_VECTOR_WIDTH_DOUBLE: 2
		CL_DEVICE_VENDOR_ID: 4294967295
		CL_DEVICE_AVAILABLE: 1
		CL_DEVICE_COMPILER_AVAILABLE: 1
		CL_DEVICE_ENDIAN_LITTLE: 1
		CL_DEVICE_ERROR_CORRECTION_SUPPORT: 0
		CL_DEVICE_IMAGE_SUPPORT: 1
		CL_DEVICE_EXECUTION_CAPABILITIES: 3
		CL_DEVICE_GLOBAL_MEM_CACHE_SIZE: 64
		CL_DEVICE_GLOBAL_MEM_SIZE: 8589934592
		CL_DEVICE_LOCAL_MEM_SIZE: 32768
		CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE: 65536
		CL_DEVICE_MAX_MEM_ALLOC_SIZE: 2147483648
		CL_DEVICE_GLOBAL_MEM_CACHE_TYPE: 2
		CL_DEVICE_IMAGE2D_MAX_HEIGHT: 8192
		CL_DEVICE_IMAGE2D_MAX_WIDTH: 8192
		CL_DEVICE_IMAGE3D_MAX_DEPTH: 2048
		CL_DEVICE_IMAGE3D_MAX_HEIGHT: 2048
		CL_DEVICE_IMAGE3D_MAX_WIDTH: 2048
		CL_DEVICE_MAX_PARAMETER_SIZE: 4096
		CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024
		CL_DEVICE_PROFILING_TIMER_RESOLUTION: 1
		CL_DEVICE_QUEUE_PROPERTIES: 2
		CL_DEVICE_TYPE: 2
		CL_DEVICE_LOCAL_MEM_TYPE: 2
		CL_DEVICE_MAX_WORK_ITEM_SIZES: (1024, 1, 1)
	 OpenCL device [1]
		CL_DEVICE_NAME: HD Graphics 5000
		CL_DEVICE_PROFILE: FULL_PROFILE
		CL_DEVICE_VENDOR: Intel
		CL_DEVICE_VERSION: OpenCL 1.2 
		CL_DRIVER_VERSION: 1.2(Dec 17 2015 21:11:49)
		CL_DEVICE_EXTENSIONS: cl_APPLE_SetMemObjectDestructor cl_APPLE_ContextLoggingFunctions cl_APPLE_clut cl_APPLE_query_kernel_names cl_APPLE_gl_sharing cl_khr_gl_event cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store cl_khr_image2d_from_buffer cl_khr_gl_depth_images cl_khr_depth_images cl_khr_3d_image_writes 
		CL_DEVICE_VERSION: OpenCL 1.2 
		CL_DEVICE_ADDRESS_BITS: 64
		CL_DEVICE_GLOBAL_MEM_CACHELINE_SIZE: 0
		CL_DEVICE_MAX_CLOCK_FREQUENCY: 1100
		CL_DEVICE_MAX_COMPUTE_UNITS: 40
		CL_DEVICE_MAX_CONSTANT_ARGS: 8
		CL_DEVICE_MAX_READ_IMAGE_ARGS: 128
		CL_DEVICE_MAX_SAMPLERS: 16
		CL_DEVICE_MAX_WORK_ITEM_DIMENSIONS: 3
		CL_DEVICE_MAX_WRITE_IMAGE_ARGS: 8
		CL_DEVICE_MEM_BASE_ADDR_ALIGN: 1024
		CL_DEVICE_MIN_DATA_TYPE_ALIGN_SIZE: 128
		CL_DEVICE_PREFERRED_VECTOR_WIDTH_CHAR: 1
		CL_DEVICE_PREFERRED_VECTOR_WIDTH_SHORT: 1
		CL_DEVICE_PREFERRED_VECTOR_WIDTH_INT: 1
		CL_DEVICE_PREFERRED_VECTOR_WIDTH_LONG: 1
		CL_DEVICE_PREFERRED_VECTOR_WIDTH_FLOAT: 1
		CL_DEVICE_PREFERRED_VECTOR_WIDTH_DOUBLE: 0
		CL_DEVICE_VENDOR_ID: 16925952
		CL_DEVICE_AVAILABLE: 1
		CL_DEVICE_COMPILER_AVAILABLE: 1
		CL_DEVICE_ENDIAN_LITTLE: 1
		CL_DEVICE_ERROR_CORRECTION_SUPPORT: 0
		CL_DEVICE_IMAGE_SUPPORT: 1
		CL_DEVICE_EXECUTION_CAPABILITIES: 1
		CL_DEVICE_GLOBAL_MEM_CACHE_SIZE: 0
		CL_DEVICE_GLOBAL_MEM_SIZE: 1610612736
		CL_DEVICE_LOCAL_MEM_SIZE: 65536
		CL_DEVICE_MAX_CONSTANT_BUFFER_SIZE: 65536
		CL_DEVICE_MAX_MEM_ALLOC_SIZE: 402653184
		CL_DEVICE_GLOBAL_MEM_CACHE_TYPE: 0
		CL_DEVICE_IMAGE2D_MAX_HEIGHT: 16384
		CL_DEVICE_IMAGE2D_MAX_WIDTH: 16384
		CL_DEVICE_IMAGE3D_MAX_DEPTH: 2048
		CL_DEVICE_IMAGE3D_MAX_HEIGHT: 2048
		CL_DEVICE_IMAGE3D_MAX_WIDTH: 2048
		CL_DEVICE_MAX_PARAMETER_SIZE: 1024
		CL_DEVICE_MAX_WORK_GROUP_SIZE: 512
		CL_DEVICE_PROFILING_TIMER_RESOLUTION: 80
		CL_DEVICE_QUEUE_PROPERTIES: 2
		CL_DEVICE_TYPE: 4
		CL_DEVICE_LOCAL_MEM_TYPE: 1
		CL_DEVICE_MAX_WORK_ITEM_SIZES: (512, 512, 512)
	 Using OpenCL device [0]
+ OpenMP (ON)
+ Parameters
	 input                                       /var/folders/b8/8bjj90812dqd2bdgzqllpmgm0000gn/T/Suzanne.off
	 resolution                                  100000
	 max. depth                                  20
	 max. concavity                              0.0025
	 plane down-sampling                         4
	 convex-hull down-sampling                   4
	 alpha                                       0.05
	 beta                                        0.05
	 gamma                                       0.00125
	 delta                                       0.05
	 pca                                         0
	 mode                                        0
	 max. vertices per convex-hull               32
	 min. volume to add vertices to convex-hulls 0.0001
	 convex-hull approximation                   1
	 OpenCL acceleration                         1
	 OpenCL platform ID                          0
	 OpenCL device ID                            0
	 output                                      /var/folders/b8/8bjj90812dqd2bdgzqllpmgm0000gn/T/Suzanne.wrl
	 log                                         /var/folders/b8/8bjj90812dqd2bdgzqllpmgm0000gn/T/Suzanne_log.txt
+ Load mesh
  0% [ Voxelization  20% ] Iteration 1   0%
  0% [ Voxelization  20% ] Iteration 1 100%
 10% [ Voxelization 100% ] Iteration 1 100%
 10% [ Compute primitive set   0% ] Convert volume to pset   0%
 15% [ Compute primitive set 100% ] Convert volume to pset 100%
 15% [ Approximate Convex Decomposition   0% ] Subdivision level 1   0%
 15% [ Approximate Convex Decomposition   0% ] Subdivision level 1   0%

**Comment by kristofgiber** [comment]
Adding more information here. I've installed the Blender add-on on Windows as well. Strangely, though it works on relatively simple objects (such as a cube with a few concave extrusions), but when I use something more complex such as a Suzanne mesh, it gives the same error message as above: 'no meshes to process!'. So I guess this message pops up for a lot of different errors and the underlying problem may or may not be related to one another. In any case, it currently doesn't work properly for neither Mac nor Windows.

**Comment by tobyndax** [comment]
I tried this out on my MacBook Air 2011, and when running the precompiled binaries result in the dyld issue. (fixable as you mentioned). Just as you the program 'halts' at subdivision, however running the no OpenCL no openmp version went fine. So try that out.

**Comment by kristofgiber** [comment]
Okay that version works indeed. Perhaps this could be added to the documentation for Mac users. Thanks anyway.
