### ISSUE TITLE
v-hacd4 ConvexHull Overlap

### ISSUE THREAD

**Issue by kt-Hou** [kmammou/v-hacd#134]
Hello, when using the V-HACD 4.0, it is found that the convex hulls will overlap.
![image](https://user-images.githubusercontent.com/85099539/196603803-741fa683-7f19-4998-aaa6-a85f3f97d8a0.png)
This is a bunny decomposed with default parameters.
Can I do the same as v3, and the convex hulls do not overlap each other?
Thank you!

**Comment by jratcliff63367** [comment]
A small amount of overlap like this is just how the algorithm works. I don't have a quick fix for this.
