### ISSUE TITLE
Need help testing the Linux build

### ISSUE THREAD

**Issue by jratcliff63367** [kmammou/v-hacd#136]
I don't really have a working Linux setup right now. Can someone verify that the project builds on Linux? I would like to push a new version out with minor fixes.

**Comment by MostHated** [comment]
You will have to forgive me, as this might be something simple, but I just don't work with C++ often (at all), but I attempted to build and got the following:

```log
CMake Error at CMakeLists.txt:7 (project):
  Generator
    Unix Makefiles
  does not support platform specification, but platform
    x64
  was specified.
-- Configuring incomplete, errors occurred!
See also "/mnt/x/GitHub/kmammou/v-hacd/app/CMakeFiles/CMakeOutput.log".
```

<details>
<summary>System Details</summary>

mosthated@pop-os
----------------
OS: Pop!_OS 22.04 LTS x86_64
Host: X670E Taichi
Kernel: 6.0.2-060002-generic
Uptime: 1 day, 16 hours, 20 mins
Packages: 4355 (dpkg), 43 (nix-default), 99 (flatpak), 14 (snap)
Shell: zsh 5.8.1
Resolution: 2560x1080
DE: GNOME 42.3.1
WM: Mutter
WM Theme: Yaru-dark
Theme: Pop-dark [GTK2/3]
Icons: Flatery-Orange-Dark [GTK2/3]
Terminal: alacritty
CPU: AMD Ryzen 9 7950X (32) @ 5.881GHz
GPU: AMD ATI Radeon RX 6800/6800 XT / 6900 XT
GPU: AMD ATI 59:00.0 Device 164e
Memory: 42380MiB / 63415MiB

</details>

**Comment by jratcliff63367** [comment]
Yeah, I need help getting that fixed.  Maybe Vilkun can take a look at it.

**Comment by MostHated** [comment]
Can confirm, I am able to build now. Thanks!
