### ISSUE TITLE
Assertion error on line 5166

### ISSUE THREAD

**Issue by HeraclitusDevotee** [kmammou/v-hacd#139]
I'm getting this assertion error: i < m_dim[0] && i >= 0 && j < m_dim[1] && j >= 0 && k < m_dim[2] && k >= 0

Any information on the cause of this would be appreciated.

**Comment by jratcliff63367** [comment]
That would be a bug. Can you please give me a repro case? Meaning a Wavefront OBJ file and the exact parameters you used?

**Comment by HeraclitusDevotee** [comment]
My mistake, I was using mesh data from a GLTF file, which I falsely assumed would have compatible values. Upon comparing the data from the two file types I realized the problem (here is sample data from a cube):

<HTML>
<BODY TEXT="#000000">
<TABLE FRAME=VOID CELLSPACING=0 COLS=4 RULES=NONE BORDER=0>
	<COLGROUP><COL WIDTH=86><COL WIDTH=86><COL WIDTH=86><COL WIDTH=86></COLGROUP>
	<TBODY>
		<TR>
			<TD WIDTH=86 HEIGHT=20 ALIGN=LEFT><FONT FACE="" SIZE=3>OBJ Verts</FONT></TD>
			<TD WIDTH=86 ALIGN=LEFT><FONT FACE="" SIZE=3>GLTF Verts</FONT></TD>
			<TD WIDTH=86 ALIGN=LEFT><FONT FACE="" SIZE=3>OBJ Index</FONT></TD>
			<TD WIDTH=86 ALIGN=LEFT><FONT FACE="" SIZE=3>GLTF Index</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=RIGHT SDVAL="-100" SDNUM="1033;"><FONT FACE="" SIZE=3>-100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="-1" SDNUM="1033;"><FONT FACE="" SIZE=3>-1</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="1" SDNUM="1033;"><FONT FACE="" SIZE=3>1</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="3" SDNUM="1033;"><FONT FACE="" SIZE=3>3</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=RIGHT SDVAL="-100" SDNUM="1033;"><FONT FACE="" SIZE=3>-100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="0" SDNUM="1033;"><FONT FACE="" SIZE=3>0</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="2" SDNUM="1033;"><FONT FACE="" SIZE=3>2</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="6" SDNUM="1033;"><FONT FACE="" SIZE=3>6</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=RIGHT SDVAL="100" SDNUM="1033;"><FONT FACE="" SIZE=3>100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="0" SDNUM="1033;"><FONT FACE="" SIZE=3>-0</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="0" SDNUM="1033;"><FONT FACE="" SIZE=3>0</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="0" SDNUM="1033;"><FONT FACE="" SIZE=3>0</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=RIGHT SDVAL="-100" SDNUM="1033;"><FONT FACE="" SIZE=3>-100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="-100" SDNUM="1033;"><FONT FACE="" SIZE=3>-100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="3" SDNUM="1033;"><FONT FACE="" SIZE=3>3</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="10" SDNUM="1033;"><FONT FACE="" SIZE=3>10</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=RIGHT SDVAL="100" SDNUM="1033;"><FONT FACE="" SIZE=3>100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="-100" SDNUM="1033;"><FONT FACE="" SIZE=3>-100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="6" SDNUM="1033;"><FONT FACE="" SIZE=3>6</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="19" SDNUM="1033;"><FONT FACE="" SIZE=3>19</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=RIGHT SDVAL="100" SDNUM="1033;"><FONT FACE="" SIZE=3>100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="100" SDNUM="1033;"><FONT FACE="" SIZE=3>100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="2" SDNUM="1033;"><FONT FACE="" SIZE=3>2</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="8" SDNUM="1033;"><FONT FACE="" SIZE=3>8</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=RIGHT SDVAL="-100" SDNUM="1033;"><FONT FACE="" SIZE=3>-100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="0.375" SDNUM="1033;"><FONT FACE="" SIZE=3>0.375</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="7" SDNUM="1033;"><FONT FACE="" SIZE=3>7</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="23" SDNUM="1033;"><FONT FACE="" SIZE=3>23</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=RIGHT SDVAL="-100" SDNUM="1033;"><FONT FACE="" SIZE=3>-100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="1" SDNUM="1033;"><FONT FACE="" SIZE=3>1</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="4" SDNUM="1033;"><FONT FACE="" SIZE=3>4</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="14" SDNUM="1033;"><FONT FACE="" SIZE=3>14</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=RIGHT SDVAL="-100" SDNUM="1033;"><FONT FACE="" SIZE=3>-100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="0" SDNUM="1033;"><FONT FACE="" SIZE=3>0</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="6" SDNUM="1033;"><FONT FACE="" SIZE=3>6</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="20" SDNUM="1033;"><FONT FACE="" SIZE=3>20</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=RIGHT SDVAL="-100" SDNUM="1033;"><FONT FACE="" SIZE=3>-100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="-1" SDNUM="1033;"><FONT FACE="" SIZE=3>-1</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="5" SDNUM="1033;"><FONT FACE="" SIZE=3>5</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="15" SDNUM="1033;"><FONT FACE="" SIZE=3>15</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=RIGHT SDVAL="100" SDNUM="1033;"><FONT FACE="" SIZE=3>100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="0" SDNUM="1033;"><FONT FACE="" SIZE=3>-0</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="0" SDNUM="1033;"><FONT FACE="" SIZE=3>0</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="2" SDNUM="1033;"><FONT FACE="" SIZE=3>2</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=RIGHT SDVAL="-100" SDNUM="1033;"><FONT FACE="" SIZE=3>-100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="-100" SDNUM="1033;"><FONT FACE="" SIZE=3>-100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="4" SDNUM="1033;"><FONT FACE="" SIZE=3>4</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="13" SDNUM="1033;"><FONT FACE="" SIZE=3>13</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=RIGHT SDVAL="100" SDNUM="1033;"><FONT FACE="" SIZE=3>100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="-100" SDNUM="1033;"><FONT FACE="" SIZE=3>-100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="6" SDNUM="1033;"><FONT FACE="" SIZE=3>6</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="18" SDNUM="1033;"><FONT FACE="" SIZE=3>18</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=RIGHT SDVAL="-100" SDNUM="1033;"><FONT FACE="" SIZE=3>-100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="100" SDNUM="1033;"><FONT FACE="" SIZE=3>100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="0" SDNUM="1033;"><FONT FACE="" SIZE=3>0</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="1" SDNUM="1033;"><FONT FACE="" SIZE=3>1</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=RIGHT SDVAL="100" SDNUM="1033;"><FONT FACE="" SIZE=3>100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="0.125" SDNUM="1033;"><FONT FACE="" SIZE=3>0.125</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="2" SDNUM="1033;"><FONT FACE="" SIZE=3>2</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="7" SDNUM="1033;"><FONT FACE="" SIZE=3>7</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=RIGHT SDVAL="100" SDNUM="1033;"><FONT FACE="" SIZE=3>100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="0.25" SDNUM="1033;"><FONT FACE="" SIZE=3>0.25</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="3" SDNUM="1033;"><FONT FACE="" SIZE=3>3</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="11" SDNUM="1033;"><FONT FACE="" SIZE=3>11</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=RIGHT SDVAL="100" SDNUM="1033;"><FONT FACE="" SIZE=3>100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="0" SDNUM="1033;"><FONT FACE="" SIZE=3>0</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="5" SDNUM="1033;"><FONT FACE="" SIZE=3>5</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="16" SDNUM="1033;"><FONT FACE="" SIZE=3>16</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=RIGHT SDVAL="100" SDNUM="1033;"><FONT FACE="" SIZE=3>100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="0" SDNUM="1033;"><FONT FACE="" SIZE=3>0</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="7" SDNUM="1033;"><FONT FACE="" SIZE=3>7</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="22" SDNUM="1033;"><FONT FACE="" SIZE=3>22</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=RIGHT SDVAL="100" SDNUM="1033;"><FONT FACE="" SIZE=3>100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="1" SDNUM="1033;"><FONT FACE="" SIZE=3>1</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="1" SDNUM="1033;"><FONT FACE="" SIZE=3>1</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="3" SDNUM="1033;"><FONT FACE="" SIZE=3>3</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=RIGHT SDVAL="-100" SDNUM="1033;"><FONT FACE="" SIZE=3>-100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="-100" SDNUM="1033;"><FONT FACE="" SIZE=3>-100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="3" SDNUM="1033;"><FONT FACE="" SIZE=3>3</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="9" SDNUM="1033;"><FONT FACE="" SIZE=3>9</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=RIGHT SDVAL="-100" SDNUM="1033;"><FONT FACE="" SIZE=3>-100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="-100" SDNUM="1033;"><FONT FACE="" SIZE=3>-100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="2" SDNUM="1033;"><FONT FACE="" SIZE=3>2</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="6" SDNUM="1033;"><FONT FACE="" SIZE=3>6</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=RIGHT SDVAL="100" SDNUM="1033;"><FONT FACE="" SIZE=3>100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="100" SDNUM="1033;"><FONT FACE="" SIZE=3>100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="3" SDNUM="1033;"><FONT FACE="" SIZE=3>3</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="10" SDNUM="1033;"><FONT FACE="" SIZE=3>10</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=RIGHT SDVAL="100" SDNUM="1033;"><FONT FACE="" SIZE=3>100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="0.375" SDNUM="1033;"><FONT FACE="" SIZE=3>0.375</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="7" SDNUM="1033;"><FONT FACE="" SIZE=3>7</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="21" SDNUM="1033;"><FONT FACE="" SIZE=3>21</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=RIGHT SDVAL="-100" SDNUM="1033;"><FONT FACE="" SIZE=3>-100</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="0" SDNUM="1033;"><FONT FACE="" SIZE=3>0</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="6" SDNUM="1033;"><FONT FACE="" SIZE=3>6</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="19" SDNUM="1033;"><FONT FACE="" SIZE=3>19</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=RIGHT SDVAL="7" SDNUM="1033;"><FONT FACE="" SIZE=3>7</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="23" SDNUM="1033;"><FONT FACE="" SIZE=3>23</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=RIGHT SDVAL="5" SDNUM="1033;"><FONT FACE="" SIZE=3>5</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="17" SDNUM="1033;"><FONT FACE="" SIZE=3>17</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=RIGHT SDVAL="4" SDNUM="1033;"><FONT FACE="" SIZE=3>4</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="14" SDNUM="1033;"><FONT FACE="" SIZE=3>14</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=RIGHT SDVAL="5" SDNUM="1033;"><FONT FACE="" SIZE=3>5</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="15" SDNUM="1033;"><FONT FACE="" SIZE=3>15</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=RIGHT SDVAL="1" SDNUM="1033;"><FONT FACE="" SIZE=3>1</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="4" SDNUM="1033;"><FONT FACE="" SIZE=3>4</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=RIGHT SDVAL="0" SDNUM="1033;"><FONT FACE="" SIZE=3>0</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="2" SDNUM="1033;"><FONT FACE="" SIZE=3>2</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=RIGHT SDVAL="6" SDNUM="1033;"><FONT FACE="" SIZE=3>6</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="18" SDNUM="1033;"><FONT FACE="" SIZE=3>18</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=RIGHT SDVAL="4" SDNUM="1033;"><FONT FACE="" SIZE=3>4</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="12" SDNUM="1033;"><FONT FACE="" SIZE=3>12</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=RIGHT SDVAL="0" SDNUM="1033;"><FONT FACE="" SIZE=3>0</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="1" SDNUM="1033;"><FONT FACE="" SIZE=3>1</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=RIGHT SDVAL="3" SDNUM="1033;"><FONT FACE="" SIZE=3>3</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="11" SDNUM="1033;"><FONT FACE="" SIZE=3>11</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=RIGHT SDVAL="1" SDNUM="1033;"><FONT FACE="" SIZE=3>1</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="5" SDNUM="1033;"><FONT FACE="" SIZE=3>5</FONT></TD>
		</TR>
		<TR>
			<TD HEIGHT=20 ALIGN=LEFT><BR></TD>
			<TD ALIGN=LEFT><BR></TD>
			<TD ALIGN=RIGHT SDVAL="5" SDNUM="1033;"><FONT FACE="" SIZE=3>5</FONT></TD>
			<TD ALIGN=RIGHT SDVAL="16" SDNUM="1033;"><FONT FACE="" SIZE=3>16</FONT></TD>
		</TR>
	</TBODY>
</TABLE>
</BODY>

</HTML>
