### ISSUE TITLE
VCOMP140.DLL is missing error 

### ISSUE THREAD

**Issue by Ali-RS** [kmammou/v-hacd#15]
Hi
in blender when i click on V-HACD and the click OK button but I got testVHACD.exe system error saying:
"The program can't start because VCOMP140.DLL is missing from your computer. Try reinstalling the program to fix this problem." 
I am on windows 10 64 bit.

**Comment by tobyndax** [comment]
You are missing some DLL's, running downloading and running a vc-redist might help.

https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by Ali-RS** [comment]
thanks so much.
It solved the problem.

I tested your V-HACD in blender and it really is awesome.
Recently this great open source 3D java game engine (jMonkeyengine) added support for your V-HACD library for physic collision.
Again thanks a lot. :heart:
