### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by Tzikas** [kmammou/v-hacd#18]
I'm creating 3D letter using THREE.TextGeometry and THREE.Mesh and would like to have it collide with other letters using Cannon.js, much like http://schteppe.github.io/cannon.js/demos/collisions.html How do I run v-hacd ?  I'm sorry for such a basic question, but I couldn't figure it out.

**Comment by clankill3r** [comment]
How far did you get?
I'm almost there, but Tzikas provided me a huge pain in the ass.

**Comment by Tzikas** [comment]
Haha what?  Sorry I gave in.  I hope you're able to get it.

**Comment by kmammou** [comment]
Please, find below an example of command line to decompose a mesh. You can also use the Blender add-on (http://www.bulletphysics.org/Bullet/phpBB3/viewtopic.php?f=4&t=6619&start=30)

./testVHACD --input camel.off --output camel_acd.wrl --log log.txt --resolution 1000000 --depth 20 --concavity 0.0025 --planeDownsampling 4 --convexhullDownsampling 4 --alpha 0.05 --beta 0.05 --gamma 0.00125 --pca 0 --mode 0 --maxNumVerticesPerCH 256 --minVolumePerCH 0.0001 --convexhullApproximation 1 --oclDeviceID 2
