### ISSUE TITLE
No Meshes to process blender when used version from sources

### ISSUE THREAD

**Issue by UndeRus** [kmammou/v-hacd#23]
After this commit 6d2d84a6b992967232a21c5641b329a3b1e0f1e0 testVHACD version built from sources stopped working cause of:

1. Now mesh exported in OBJ format
2. Blender trying to import VRML format(https://github.com/kmammou/v-hacd/blob/master/add-ons/blender/object_vhacd.py#L289)

I can't send pull request because it break compatibility with already existing binaries for Windows/OSX, so bugfix must  contain blender plugin fix and updated binaries.

**Comment by clankill3r** [comment]
Do you know how I can get it working on OSX?

**Comment by kmammou** [comment]
I have just committed a fix, to generate either an OBJ or VRML2 file based on the output extension. Please,  could you test?
