### ISSUE TITLE
How to get more accurate results

### ISSUE THREAD

**Issue by clankill3r** [kmammou/v-hacd#25]
Let's take the default torus:
<img width="656" alt="screen shot 2016-12-28 at 15 12 48" src="https://cloud.githubusercontent.com/assets/738650/21532142/a94a258e-cd4d-11e6-9a3e-a950ad712580.png">

What is better, higher or lower downsampling values?
What does the bias do?

I try to get better results but they all look pretty simuliar cause I have no clue what i'm doing.

**Comment by kmammou** [comment]
I would recommend reading the following book chapter to better understand the details
"Game Engine Gems 3: Volumetric Hierarchical Approximate Convex Decomposition".

A number of parameters could influence the precision. The main ones in order of importance:
- concavity 
- resolution
- planeDownsampling and
- convexhullDownsampling.
