### ISSUE TITLE
Add Parameters To The Examples

### ISSUE THREAD

**Issue by calben** [kmammou/v-hacd#27]
I think it would be monumentally helpful if the paramaters used to generate the demos could be provided.
I'm having a hard time figuring out how to get the plugin to produce more than 3 or 4 rough hulls of my object!

Would appreciate it!

**Comment by kmammou** [comment]
try setting depth to small value, e.g., 2 (see below)

testVHACD --input ../../bunny_closed.off --output bunny_ocl-opm_16M_1.wrl --log bunny_ocl-opm_log_16M_1.txt --resolution 16000000 --depth 2 --concavity 0.0025 --planeDownsampling 4 --convexhullDownsampling 4 --alpha 0.05 --beta 0.05 --gamma 0.0 --pca 0 --mode 0 --maxNumVerticesPerCH 1024 --minVolumePerCH 0.0 --convexhullApproximation 1
