### ISSUE TITLE
Hulls usually extend past model

### ISSUE THREAD

**Issue by pushrax** [kmammou/v-hacd#29]
Quite often, hulls are generated that are larger than the model, even if the model has a perfect hull within the constraints. Example dodecahedron:

![screen shot 2017-01-13 at 15 09 27](https://cloud.githubusercontent.com/assets/984857/21944173/c4b20d8a-d9a2-11e6-88e1-b729bc82c9af.png)

Is there a recommended way to tune V-HACD to avoid this? Is increasing the voxel resolution the only option?

**Comment by kmammou** [comment]
Yes. Increasing voxel number is a possible solution.

**Comment by kmammou** [comment]
You can also try shrinking the convex hulls by the half size of a voxel.

**Comment by pushrax** [comment]
Do you mean by using the btConvexHullComputer shrink parameter?

**Comment by kmammou** [comment]
I was thinking you can apply it to the hulls the algorithm generates. Just move the points of each hull toward their centroid.

**Comment by pushrax** [comment]
That works fine, thanks.
