### ISSUE TITLE
run.py and OpenCL issues

### ISSUE THREAD

**Issue by consultit** [kmammou/v-hacd#50]
Hi, I tried to build the binary on my GNU/Linux Debian 9.3 with NVIDIA 970 graphics card (driver 375.82) and I encountered these issues:

1) the original `install/run.py` script does not work, but replacing in the `cmake` fuction, the line `cmd = "cmake" + arg + "../" + src_dir` with `cmd = [" cmake ", arg," ../ "+ src_dir]` everything works fine

2) after having successfully built the binary and then installed and configured the add-on in Blender (2.78a), I have decomposed the `Suzanne` monkey successfully, but in the log 
[Suzanne_log.txt](https://github.com/kmammou/v-hacd/files/1611382/Suzanne_log.txt)
 have resulted some OpenCL related errors.

bye

**Comment by consultit** [comment]
Hi after analyzing a bit I saw that the OpenCL issue is due to the `int32_t` type declarations in the kernel program `oclProgramSource` in `src/VHACD_lib/src/VHACD.cpp`. 
I solved by changing them with the `int` standard scalar type as described [here](https://www.khronos.org/registry/OpenCL/sdk/1.1/docs/man/xhtml/scalarDataTypes.html). 
I attached a simple `git diff master` with latest commit. 
[opencl-correction.diff.txt](https://github.com/kmammou/v-hacd/files/1749110/opencl-correction.diff.txt)
Bye

**Comment by tobyndax** [comment]
Hi Consultit, consider forking, applying the updates you've discussed above and issue a pullrequest against the original repo. 

Best Regards Jens Edhammer

**Comment by kmammou** [comment]
Hi Jens, That would be great. Please, do.
