### ISSUE TITLE
Utilizing the plugin via scripting

### ISSUE THREAD

**Issue by btickell** [kmammou/v-hacd#68]
For my use case, it would be helpful to run the add-on on all selected mesh objects via a blender python script. 

I need to generate hulls for a large number of object meshes and export each component to a seperate `.stl` file so being able to programmatically invoke v-hacd would be helpful.

**Comment by btickell** [comment]
I can see a possible solution being take the `execute()` method from the addon script and plopping that into my blender script, is this the best approach?

**Comment by tobyndax** [comment]
There are binaries in the repository, check what input and output they take/produce. If this matches your use-case doing this from pure python, or bash, or batch files will be easier than using Blender.
