### ISSUE TITLE
How to cite this library?

### ISSUE THREAD

**Issue by submagr** [kmammou/v-hacd#86]
I cannot find a proper citation for this library. Can you share one if there?

**Comment by submagr** [comment]
Hi @kmammou,
Any comments on this?

Thanks for creating this amazing library.

**Comment by kmammou** [comment]
Hi, please you could reference this book chapter

Volumetric Hierarchical Approximate Convex Decomposition  In Game Engine Gems 3, A K Peters, 2016, pp. 141–158.
--
